Fix CI and generic go workflow
GoogleContainerTools/kpt-functions-catalog pull request #118
Opened 2020-11-05 03:12 UTC by prachirp

2020-11-05 17:21 UTC, Shell32-Natsu approved these changes

2020-11-05 17:32 UTC, frankfarzan requested changes

2020-11-05 17:32 UTC, frankfarzan commented on functions/go/publish-functions.sh
> +  [[ -z "${BUILDONLY}" ]] && {
use an if statement here

2020-11-05 17:32 UTC, frankfarzan commented on .github/workflows/ci.yaml
> +        cd ../go
create a separate step for building Go images

2020-11-06 19:32 UTC, frankfarzan approved these changes

2020-11-06 19:34 UTC, merged