put-setter-values function
GoogleContainerTools/kpt-functions-catalog pull request #464
Opened 2021-07-07 05:08 UTC by phanimarupaka

Introduce a new function put-setter-values to the catalog.

2021-07-07 20:26 UTC, frankfarzan requested changes

2021-07-07 20:26 UTC, frankfarzan commented on examples/put-setter-values-simple/README.md
> +$ kpt pkg get https://github.com/GoogleContainerTools/kpt-functions-catalog.git/examples/put-setter-values-simple
are the packages versioned correctly post-merge?

2021-07-07 20:26 UTC, frankfarzan commented on functions/go/put-setter-values/README.md
> +Put setter values in Kptfile or functionConfig for setters.
I would rephrase this for more clarity. Also the fact the the functionConfig is inlined in Kptfile or not shouldn't be the important thing, so may want to remove that.

2021-07-07 20:26 UTC, frankfarzan commented on functions/go/put-setter-values/README.md
> +This function is meant to be used as an alternative to editing file directly to declare
"edit the file" Be more precise, what file are you talking about?

2021-07-07 20:26 UTC, frankfarzan commented on functions/go/put-setter-values/README.md
> +Modified setters.yaml looks like the following:
setters.yaml -> `setters.yaml`

2021-07-07 20:26 UTC, frankfarzan commented on functions/go/put-setter-values/putsettervalues/putsettervalues.go
> +// Filter implements Set as a yaml.Filter
comment on what this function does

2021-07-07 20:26 UTC, frankfarzan commented on functions/go/put-setter-values/putsettervalues/putsettervalues_test.go
> +      configPath: setters.yaml
have a test case for when setters.yaml is in a nested directory in the package.

2021-07-07 23:41 UTC, phanimarupaka commented
@mengqiy verify-docs should not fail here. The function is supposed to be used by imperative invocation. PTAL.

2021-07-09 17:55 UTC, mengqiy commented
We are going to have a meta function!

> @mengqiy verify-docs should not fail here. The function is supposed to be used by imperative invocation. PTAL.

I will fix it today.

2021-08-19 00:05 UTC, closed without merging