Fix starlark function to not drop id annotation
GoogleContainerTools/kpt-functions-catalog pull request #473
Opened 2021-07-13 19:55 UTC by mengqiy

2021-07-13 21:19 UTC, droot requested changes

2021-07-13 21:19 UTC, droot commented on functions/go/starlark/third_party/sigs.k8s.io/kustomize/kyaml/fn/runtime/starlark/starlark.go
> +type SimpleFilter struct {
I wonder if we can add a test case ensuring annotations are preserved.

2021-07-14 03:45 UTC, mengqiy commented
Rebased on #474 and added a test.

2021-07-14 19:27 UTC, droot approved these changes

2021-07-14 19:55 UTC, merged